# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jack/Code/DevTraining/Apps/Orbits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jack/Code/DevTraining/Apps/Orbits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Code/DevTraining/Apps/Orbits/CMakeFiles /home/jack/Code/DevTraining/Apps/Orbits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Code/DevTraining/Apps/Orbits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OrbitSim

# Build rule for target.
OrbitSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OrbitSim
.PHONY : OrbitSim

# fast build rule for target.
OrbitSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/build
.PHONY : OrbitSim/fast

Orbits.o: Orbits.cc.o
.PHONY : Orbits.o

# target to build an object file
Orbits.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/Orbits.cc.o
.PHONY : Orbits.cc.o

Orbits.i: Orbits.cc.i
.PHONY : Orbits.i

# target to preprocess a source file
Orbits.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/Orbits.cc.i
.PHONY : Orbits.cc.i

Orbits.s: Orbits.cc.s
.PHONY : Orbits.s

# target to generate assembly for a file
Orbits.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/Orbits.cc.s
.PHONY : Orbits.cc.s

src/RunManager.o: src/RunManager.cc.o
.PHONY : src/RunManager.o

# target to build an object file
src/RunManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/src/RunManager.cc.o
.PHONY : src/RunManager.cc.o

src/RunManager.i: src/RunManager.cc.i
.PHONY : src/RunManager.i

# target to preprocess a source file
src/RunManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/src/RunManager.cc.i
.PHONY : src/RunManager.cc.i

src/RunManager.s: src/RunManager.cc.s
.PHONY : src/RunManager.s

# target to generate assembly for a file
src/RunManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OrbitSim.dir/build.make CMakeFiles/OrbitSim.dir/src/RunManager.cc.s
.PHONY : src/RunManager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OrbitSim"
	@echo "... Orbits.o"
	@echo "... Orbits.i"
	@echo "... Orbits.s"
	@echo "... src/RunManager.o"
	@echo "... src/RunManager.i"
	@echo "... src/RunManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

