name: Check Build

on:
  push:
    branches:
      - develop
      - feature/*
      - bugfix/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set working directory
        working-directory: ./simulation
      
      - name: Install root
        run: ./scripts/installroot.sh

      - name: configure
        run: source scripts/env.sh
    
      - name: make
        run: make

